### ISSUE TITLE
libglew, gl4es, freeglut and glu (OpenGL)  They don't want to work in termux

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#394]
**Problem description**

The window comes out for a few seconds and then disappears

![Screenshot_20210726-122626](https://user-images.githubusercontent.com/64093255/127032377-f4cc25ec-1f05-49ea-aeb5-eefc9f4f893d.png)

Info:
Android 8.0 32 bits
2GB of ram
DE: lxqt
WM: Openbox 
Using vnc

In proot it works, but in termux anything related to OpenGL does not want to work

**Steps to reproduce**

**Expected behavior**

**Comment by Yisus7u7** [comment]
@suhan-paradkar

**Comment by xeffyr** [comment]
VNC doesn't have GLX extension. So forget about anything that uses GLX at least until someone manages to get it working.

**Comment by Yisus7u7** [comment]
> VNC doesn't have GLX extension. So forget about everything that uses GLX at least until someone manages to get it working.
I've seen people in the reddit group who do it, and it works well for them.

**Comment by xeffyr** [comment]
They probably used XSDL.

**Comment by Yisus7u7** [comment]
No, is vnc:

https://www.reddit.com/r/termux/comments/on4fkp/openglglfw_gears_on_termux_x11_no_root/?utm_medium=android_app&utm_source=share

**Comment by xeffyr** [comment]
Here is an output of `xdpyinfo`:
![Screenshot_20210726-215956](https://user-images.githubusercontent.com/25881154/127044060-f1611ab3-7460-4c25-af43-1251de352be5.png)

There no GLX and I even has disabled it intentionally for tigervnc which uses same build options as `xorg-xvfb-server`.

**Comment by xeffyr** [comment]
What is on reddit is GLFW examples and not `glxgears`.

**Comment by Yisus7u7** [comment]
The GLFW examples also happen to you

**Comment by xeffyr** [comment]
@Yisus7u7 I really have no idea whether freeglut works or not. These packages were added as requested and since then I didn't get any reports about whether they actually work or not.

**Comment by Yisus7u7** [comment]
Oh ok :(

**Comment by xeffyr** [comment]
I just got `glxgears` working ([sources](https://github.com/JoakimSoderberg/mesademos/blob/master/src/xdemos/glxgears.c)). So it may rather depend on where you got it and how it was compiled, but not on GLX extension presence.

![Screenshot_20210726-221437](https://user-images.githubusercontent.com/25881154/127045923-4595e77e-a788-4630-9445-1888447e21e6.png)

**Comment by Yisus7u7** [comment]
Thanks

**Comment by DevAgentA** [comment]
@Yisus7u7 maybe because you're on arm32

**Comment by Yisus7u7** [comment]
> @Yisus7u7 maybe because you're on arm32

Why?

**Comment by Yisus7u7** [comment]
![Screenshot_20210928-114239](https://user-images.githubusercontent.com/64093255/135129936-02cb98e3-e66c-4b52-9eeb-75dd4dc0dbc4.png)

@xeffyr I tried the one in that repository and it doesn't work either.

**Comment by AbdullahBinJahed** [comment]
> > @Yisus7u7 maybe because you're on arm32
> 
> Why?

mesa-demos does work on aarch ... it just doesn't work on 32bit arm cpu

**Comment by Yisus7u7** [comment]
> > > @Yisus7u7 maybe because you're on arm32
> > 
> > 
> > Why?
> 
> mesa-demos does work on aarch ... it just doesn't work on 32bit arm cpu

Then you have to see what the problem is and create patches.

**Comment by AbdullahBinJahed** [comment]
> > > > @Yisus7u7 maybe because you're on arm32
> > > 
> > > 
> > > Why?
> > 
> > 
> > mesa-demos does work on aarch ... it just doesn't work on 32bit arm cpu
> 
> Then you have to see what the problem is and create patches.

If I was smart enough to do that I would've already done that 🥴 ...

someone did help me to native compile the mesa library and I think it worked probably ... but no way to test it ...

can you give me a test program to check wheather OpenGL works or not ?

**Comment by Yisus7u7** [comment]
> > > > > @Yisus7u7 maybe because you're on arm32
> > > > 
> > > > 
> > > > Why?
> > > 
> > > 
> > > mesa-demos does work on aarch ... it just doesn't work on 32bit arm cpu
> > 
> > 
> > Then you have to see what the problem is and create patches.
> 
> If I was smart enough to do that I would've already done that 🥴 ...
> 
> someone did help me to native compile the mesa library and I think it worked probably ... but no way to test it ...
> 
> can you give me a test program to check wheather OpenGL works or not ?

https://github.com/davidanthonygardner/glxgears

Try compiling and running that

**Comment by AbdullahBinJahed** [comment]
> > > > > > @Yisus7u7 maybe because you're on arm32
> > > > > 
> > > > > 
> > > > > Why?
> > > > 
> > > > 
> > > > mesa-demos does work on aarch ... it just doesn't work on 32bit arm cpu
> > > 
> > > 
> > > Then you have to see what the problem is and create patches.
> > 
> > 
> > If I was smart enough to do that I would've already done that 🥴 ...
> > someone did help me to native compile the mesa library and I think it worked probably ... but no way to test it ...
> > can you give me a test program to check wheather OpenGL works or not ?
> 
> https://github.com/davidanthonygardner/glxgears
> 
> Try compiling and running that

haha wth ... now even linking doesn't work ? I'll have to recompile it then check
btw link for the script is is previous comment, could you check it works or not ?
![Screenshot_2021-09-29-05-29-06-812_com termux](https://user-images.githubusercontent.com/39275638/135179179-3a98d6e5-6deb-4963-8f78-491d89363b3e.jpg)

**Comment by Yisus7u7** [comment]
I also had that mistake once I compiled mesa... 

I think bookstores are broken.

**Comment by AbdullahBinJahed** [comment]
> I also had that mistake once I compiled mesa...
> 
> I think bookstores are broken.
ah nvm ... removing ndk-multilib fixed it ...
![Screenshot_2021-09-29-05-37-32-411_com termux](https://user-images.githubusercontent.com/39275638/135179704-87b36ee6-58e5-4489-a8eb-84a93397bace.jpg)

**Comment by NoNameMan1231** [comment]
it works on proot-distro!

**Comment by NoNameMan1231** [comment]
> it works on proot-distro!

maybe Termux problem?

**Comment by AbdullahBinJahed** [comment]
> it works on proot-distro!

how exactly ? on a 32 bit arm device ? can you give me exact instructions ?

**Comment by AbdullahBinJahed** [comment]
> **Problem description**
> 
> The window comes out for a few seconds and then disappears
> 
> ![Screenshot_20210726-122626](https://user-images.githubusercontent.com/64093255/127032377-f4cc25ec-1f05-49ea-aeb5-eefc9f4f893d.png)
> 
> Info: Android 8.0 32 bits 2GB of ram DE: lxqt WM: Openbox Using vnc
> 
> In proot it works, but in termux anything related to OpenGL does not want to work
> 
> **Steps to reproduce**
> 
> **Expected behavior**

can you give me the link to that wallpaper ?

**Comment by NoNameMan1231** [comment]
> > it works on proot-distro!
> 
> how exactly ? on a 32 bit arm device ? can you give me exact instructions ?

no, i use arm64 but you can view this vid:

https://www.youtube.com/watch?v=PO75bU3zGm0&t=709s

**Comment by AbdullahBinJahed** [comment]
> > > it works on proot-distro!
> > 
> > 
> > how exactly ? on a 32 bit arm device ? can you give me exact instructions ?
> 
> no, i use arm64 but you can view this vid:
> 
> https://www.youtube.com/watch?v=PO75bU3zGm0&t=709s

on arm64 OpenGL works even normally ... no need for proot-distro

**Comment by Yisus7u7** [comment]
> > > > it works on proot-distro!
> > > 
> > > 
> > > how exactly ? on a 32 bit arm device ? can you give me exact instructions ?
> > 
> > 
> > no, i use arm64 but you can view this vid:
> > https://www.youtube.com/watch?v=PO75bU3zGm0&t=709s
> 
> on arm64 OpenGL works even normally ... no need for proot-distro

Very true, the problem is 32-bit.

**Comment by AbdullahBinJahed** [comment]
> > > > > it works on proot-distro!
> > > > 
> > > > 
> > > > how exactly ? on a 32 bit arm device ? can you give me exact instructions ?
> > > 
> > > 
> > > no, i use arm64 but you can view this vid:
> > > https://www.youtube.com/watch?v=PO75bU3zGm0&t=709s
> > 
> > 
> > on arm64 OpenGL works even normally ... no need for proot-distro
> 
> Very true, the problem is 32-bit.

umm ... can i have the wallpaper link ?

**Comment by NoNameMan1231** [comment]
im sumitted a [problem](https://github.com/ptitSeb/gl4es/issues/342) in gl4es 

let's wait for respnse.

**Comment by Yisus7u7** [comment]
> umm ... can i have the wallpaper link ?

https://github.com/Yisus7u7/monas_chinas_uwu_uwu

**Comment by AbdullahBinJahed** [comment]
> > umm ... can i have the wallpaper link ?
> 
> https://github.com/Yisus7u7/monas_chinas_uwu_uwu

bro... which is the one in the xfce desktop wallpaper ?

**Comment by AbdullahBinJahed** [comment]
> > umm ... can i have the wallpaper link ?
> 
> https://github.com/Yisus7u7/monas_chinas_uwu_uwu

Thank you very much ... 🙂

![Screenshot_2021-09-29-10-01-28-916_com realvnc viewer android](https://user-images.githubusercontent.com/39275638/135201287-ce7abac4-4bc0-47cd-8e01-ef67703f07db.jpg)

**Comment by NoNameMan1231** [comment]
@yisus7u7 do your phone has access son gl4es hardware?

**Comment by xeffyr** [comment]
> https://github.com/termux/x11-packages/issues/394#issuecomment-929698169

Here is how I compiled `glxgears` (I intentionally mentioned only the .c file and not the whole repo):
```
~ $ curl -LO https://github.com/JoakimSoderberg/mesademos/raw/master/src/xdemos/glxgears.c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0   1029      0 --:--:-- --:--:-- --:--:--  1033
100 21237  100 21237    0     0  86261      0 --:--:-- --:--:-- --:--:-- 86261
~ $ clang glxgears.c -o glxgears -lGL -lX11 -lm
```

**Comment by Yisus7u7** [comment]
![Screenshot_20210929-081316](https://user-images.githubusercontent.com/64093255/135275350-30101c43-2ee3-4a93-b4ac-7ba7ea3f1a77.png)

@xeffyr just doesn't work on arm (32-bit)

**Comment by AbdullahBinJahed** [comment]
> ![Screenshot_20210929-081316](https://user-images.githubusercontent.com/64093255/135275350-30101c43-2ee3-4a93-b4ac-7ba7ea3f1a77.png)
> 
> @xeffyr just doesn't work on arm (32-bit)

give me your some way to contact you like Facebook/telegram/discord or something

**Comment by Yisus7u7** [comment]
According to this comment

https://github.com/ptitSeb/gl4es/issues/342#issuecomment-931310418

Could it be that disabling glx and mesa-dri has to do with this?

**Comment by Yisus7u7** [comment]
> @Yisus7u7 It **works** on AArch64, i686 and x86_64. So nothing to do with it. But note that gl4es is broken completely, see #442 for details.

It's not just gl4es, glu, freeglut, glew and other openGL-related libraries not working

**Comment by sukualam** [comment]
I try glxgears on xwayland (use termux x11 app) and it crash too (Segmentation Fault)

I use 32 bit prefix termux bootstrap (my device actually 64 bit)

On 64 bit termux bootstrap (default) glxgears works fine in xwayland

**Comment by sukualam** [comment]
https://github.com/termux/termux-x11/releases

**Comment by AbdullahBinJahed** [comment]
> https://github.com/termux/termux-x11/releases

it is giving me errors when i run ``` termux-x11 ``` in Termux ... maybe it's because i downloaded Termux from F-Droid ? if so then do i need to install Termux from GitHub ? but I don't have a pc ? can i compile Termux from Termux or AIDE ?

**Comment by AbdullahBinJahed** [comment]
> Use termux from fdroid is fine, i also from fdroid too, its not problem... you need to install termux-x11.deb inside termux

why this error ?

![Screenshot_2021-10-09-06-27-15-493_com termux](https://user-images.githubusercontent.com/39275638/136637231-580fac1b-f033-4623-830c-77ffc4e2f7a6.jpg)

**Comment by sukualam** [comment]
> > Use termux from fdroid is fine, i also from fdroid too, its not problem... you need to install termux-x11.deb inside termux
> 
> why this error ?
> 
> ![Screenshot_2021-10-09-06-27-15-493_com termux](https://user-images.githubusercontent.com/39275638/136637231-580fac1b-f033-4623-830c-77ffc4e2f7a6.jpg)

Download from github action, use the latest build
https://github.com/termux/termux-x11/actions

**Comment by AbdullahBinJahed** [comment]
@sukualam what now ?

![Screenshot_2021-10-09-06-55-34-881_com termux](https://user-images.githubusercontent.com/39275638/136638415-b45cad5c-c554-42d3-9e46-2c5f45f0c573.jpg)
![Screenshot_2021-10-09-07-02-27-250_com termux](https://user-images.githubusercontent.com/39275638/136638417-8dd95cd2-ea9b-4699-a202-c71919ef6c00.jpg)

**Comment by truboxl** [comment]
I try adding `TERMUX_DEBUG_BUILD=true` into https://github.com/termux/x11-packages/blob/master/packages/mesa/build.sh

Rebuild, install and use gdb to get these outputs
I tested this on aarch64 but installing arm32 Termux app from https://github.com/termux/termux-app/actions and it's reproducible
So pretty much confirm arm32 Mesa is broken
```
Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
ed/stable 1.17-4 arm [upgradable from: 1.17]
nano/stable 5.9 arm [upgradable from: 5.8]
pcre2/stable 10.38 arm [upgradable from: 10.37]
termux-tools/stable 0.141 all [upgradable from: 0.140]
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22274331 #1 SMP PREEMPT Tue Sep 7 18:27:31 +07 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A307GN
```
```
Starting program: /data/data/com.termux/files/usr/bin/glxdemo 
[New LWP 16252]

Thread 1 "glxdemo" received signal SIGSEGV, Segmentation fault.
glShadeModel (mode=7424)
    at /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h:2981
2981	/home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h: (undocumented errno 2).
Continuing.
[New LWP 16253]
[New LWP 16254]
[LWP 16254 exited]
[LWP 16253 exited]

Thread 1 "glxdemo" received signal SIGSEGV, Segmentation fault.
glShadeModel (mode=7424)
    at /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h:2981
2981	in /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h
#0  glShadeModel (mode=7424)
    at /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h:2981
        _tbl = 0x0
        _func = <optimized out>
#1  0xaaaaa97e in main (argc=<optimized out>, argv=<optimized out>)
    at /home/builder/.termux-build/mesa-demos/src/src/xdemos/glxdemo.c:120
        dpy = 0xf742fa00
        win = 2097154
```
```
Starting program: /data/data/com.termux/files/usr/bin/glinfo 

Program received signal SIGSEGV, Segmentation fault.
glDrawBuffer (mode=1028)
    at /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h:3156
3156	/home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h: (undocumented errno 2).
Continuing.
[New LWP 4808]
[New LWP 4809]
[LWP 4809 exited]
[LWP 4808 exited]

Thread 1 "glinfo" received signal SIGSEGV, Segmentation fault.
glDrawBuffer (mode=1028)
    at /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h:3156
3156	in /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h
#0  glDrawBuffer (mode=1028)
    at /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h:3156
        _tbl = 0x0
        _func = <optimized out>
#1  0xf6aea19c in fgOpenWindow () from /data/data/com.termux/files/usr/lib/libglut.so
No symbol table info available.
#2  0xf6ae87b0 in fgCreateWindow () from /data/data/com.termux/files/usr/lib/libglut.so
No symbol table info available.
#3  0xf6aea236 in glutCreateWindow ()
   from /data/data/com.termux/files/usr/lib/libglut.so
No symbol table info available.
#4  0xaaaaa674 in main (argc=1, argv=0xfffef2c4)
    at /home/builder/.termux-build/mesa-demos/src/src/demos/glinfo.c:18
No locals.
```
```
Starting program: /data/data/com.termux/files/usr/bin/glxinfo 

Program received signal SIGSEGV, Segmentation fault.
glGetString (name=7936)
    at /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h:3667
3667	/home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h: (undocumented errno 2).
Continuing.
[New LWP 5387]
[New LWP 5389]
[LWP 5389 exited]
[LWP 5387 exited]

Thread 1 "glxinfo" received signal SIGSEGV, Segmentation fault.
glGetString (name=7936)
    at /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h:3667
3667	in /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h
#0  glGetString (name=7936)
    at /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h:3667
        _tbl = 0x0
        _func = <optimized out>
#1  0xaaaac34e in print_screen_info (dpy=0xf742fa00, scrnum=0, opts=0xfffef258, 
    coreProfile=<optimized out>, es2Profile=0, limits=0, coreWorked=0)
    at /home/builder/.termux-build/mesa-demos/src/src/xdemos/glxinfo.c:468
        serverVersion = 0xf70766b0 <Fake_glXQueryServerString.version> "1.4 Mesa 17.3.9"
        clientVersion = 0xf70762c8 <Fake_glXGetClientString.version> "1.4 Mesa 17.3.9"
        glRenderer = <optimized out>
        displayName = <optimized out>
        glVendor = <optimized out>
        glExtensions = <optimized out>
        period = <optimized out>
        glxExtensions = 0xf6fe74fb "GLX_MESA_copy_sub_buffer GLX_MESA_pixmap_colormap GLX_MESA_release_buffers GLX_ARB_create_context GLX_ARB_get_proc_address GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_SGI"...
        glVersion = <optimized out>
        colon = <optimized out>
        extfuncs = {GetProgramivARB = <optimized out>, GetStringi = <optimized out>, 
          GetConvolutionParameteriv = <optimized out>}
        serverVendor = 0xf6fe74d9 "Brian Paul"
        serverExtensions = 0xf6fe74fb "GLX_MESA_copy_sub_buffer GLX_MESA_pixmap_colormap GLX_MESA_release_buffers GLX_ARB_create_context GLX_ARB_get_proc_address GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_SGI"...
        clientVendor = 0xf6fe74d9 "Brian Paul"
        clientExtensions = 0xf6fe74fb "GLX_MESA_copy_sub_buffer GLX_MESA_pixmap_colormap GLX_MESA_release_buffers GLX_ARB_create_context GLX_ARB_get_proc_address GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_SGI"...
        glxVersionMajor = <optimized out>
        glxVersionMinor = <optimized out>
        height = 100
        width = 100
        ctx = 0xf70b61c0
        root = <optimized out>
        oglstring = 0xaaaae58c "OpenGL"
        fbconfigs = <optimized out>
        visinfo = <optimized out>
        mask = 10250
        attr = {background_pixmap = 2863353856, background_pixel = 0, 
          border_pixmap = 1, border_pixel = 0, bit_gravity = 40, 
          win_gravity = -147447808, backing_store = 0, backing_planes = 4294898232, 
          backing_pixel = 4147188316, save_under = -69032, event_mask = 163840, 
          do_not_propagate_mask = 1, override_redirect = -148363805, 
          colormap = 2097153, cursor = 4148361728}
        win = 2097154
#2  0xaaaac014 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/builder/.termux-build/mesa-demos/src/src/xdemos/glxinfo.c:1261
        opts = {mode = Normal, findBest = 0 '\000', limits = 0 '\000', 
          singleLine = 0 '\000', displayName = 0x0, allowDirect = 1 '\001'}
        dpy = 0xf742fa00
        numScreens = 1
        scrnum = 0
        coreWorked = <optimized out>
```
```
Starting program: /data/data/com.termux/files/usr/bin/glxgears 
[New LWP 5771]

Thread 1 "glxgears" received signal SIGSEGV, Segmentation fault.
glLightfv (light=16384, pname=4611, params=0xaaaaf000 <init.pos>)
    at /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h:2862
2862	/home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h: (undocumented errno 2).
Continuing.
[New LWP 5773]
[New LWP 5774]
[LWP 5774 exited]
[LWP 5773 exited]

Thread 1 "glxgears" received signal SIGSEGV, Segmentation fault.
glLightfv (light=16384, pname=4611, params=0xaaaaf000 <init.pos>)
    at /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h:2862
2862	in /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h
#0  glLightfv (light=16384, pname=4611, params=0xaaaaf000 <init.pos>)
    at /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h:2862
        _tbl = 0x0
        _func = <optimized out>
#1  0xaaaab8d8 in init ()
    at /home/builder/.termux-build/mesa-demos/src/src/xdemos/glxgears.c:398
        pos = {5, 5, 10, 0}
        red = {0.800000012, 0.100000001, 0, 1}
        green = {0, 0.800000012, 0.200000003, 1}
        blue = {0.200000003, 0.200000003, 1, 1}
#2  0xaaaab4c4 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/builder/.termux-build/mesa-demos/src/src/xdemos/glxgears.c:790
        winWidth = <optimized out>
        winHeight = <optimized out>
        x = <optimized out>
        y = <optimized out>
        i = <optimized out>
        printInfo = 0 '\000'
        dpyName = <optimized out>
        dpy = 0xf742fa00
        visId = <optimized out>
        ctx = 0xf70f21c0
        win = 2097154
#0  glLightfv (light=16384, pname=4611, params=0xaaaaf000 <init.pos>)
    at /home/builder/.termux-build/mesa/src/src/mapi/glapi/glapi_mapi_tmp.h:2862
        _tbl = 0x0
        _func = <optimized out>
#1  0xaaaab8d8 in init ()
    at /home/builder/.termux-build/mesa-demos/src/src/xdemos/glxgears.c:398
        pos = {5, 5, 10, 0}
        red = {0.800000012, 0.100000001, 0, 1}
        green = {0, 0.800000012, 0.200000003, 1}
        blue = {0.200000003, 0.200000003, 1, 1}
#2  0xaaaab4c4 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/builder/.termux-build/mesa-demos/src/src/xdemos/glxgears.c:790
        winWidth = <optimized out>
        winHeight = <optimized out>
        x = <optimized out>
        y = <optimized out>
        i = <optimized out>
        printInfo = 0 '\000'
        dpyName = <optimized out>
        dpy = 0xf742fa00
        visId = <optimized out>
        ctx = 0xf70f21c0
        win = 2097154
```
Not sure how useful are these logs. Might be a red herring.

**Comment by Yisus7u7** [comment]
![Screenshot_20211016-152508](https://user-images.githubusercontent.com/64093255/137601417-26228ba0-6245-4aee-9acf-50b9b9840cc4.png)
![Screenshot_20211016-152816](https://user-images.githubusercontent.com/64093255/137601418-e74a9f84-467b-4376-93a3-efdfdcc3dc39.png)

@xeffyr Posh Shell (proot) has no problem running openGL, so the error will be that any specific hardware/driver cannot be accessed?

**Comment by Yisus7u7** [comment]
![Screenshot_20211017-165820](https://user-images.githubusercontent.com/64093255/137646590-bb603e86-08e9-4608-9e17-3c286ae5e1f3.png)
![Screenshot_20211017-165749](https://user-images.githubusercontent.com/64093255/137646591-b6ebcdf9-7850-4340-a955-d522f453c868.png)

@xeffyr Solved! 
Turn on mesa hardware acceleration

https://gxmersam.blogspot.com/p/getting-hardware-acceleration-on-termux.html?m=1

**Comment by Yisus7u7** [comment]
![Screenshot_20211017-170718](https://user-images.githubusercontent.com/64093255/137646658-dd076f78-042e-4c55-95bd-493757346a93.png)

![Screenshot_20211017-170626](https://user-images.githubusercontent.com/64093255/137646663-771e4da0-2b70-4158-9dc6-875a0002969f.png)

Enabling on mesa hardware acceleration

**Comment by Yisus7u7** [comment]
The performance is excellent, there is no lag, everything goes very fast

**Comment by DLC01** [comment]
![IMG_20211018_105206](https://user-images.githubusercontent.com/74525818/137673723-4d6d7d68-d5a5-4f19-ad5c-944f2bb04180.jpg)
![IMG_20211018_105117](https://user-images.githubusercontent.com/74525818/137673745-d22a9a13-4a74-48c4-8aa7-a83e4005fe51.jpg)
this was using the Zink driver

**Comment by sukualam** [comment]
> ![IMG_20211018_105206](https://user-images.githubusercontent.com/74525818/137673723-4d6d7d68-d5a5-4f19-ad5c-944f2bb04180.jpg) ![IMG_20211018_105117](https://user-images.githubusercontent.com/74525818/137673745-d22a9a13-4a74-48c4-8aa7-a83e4005fe51.jpg) this was using the Zink driver

Can it work on Adreno 506?

**Comment by NoNameMan1231** [comment]
You can try [this](https://youtu.be/PO75bU3zGm0) in chroot

**Comment by AbdullahBinJahed** [comment]
> > > The performance is excellent, there is no lag, everything goes very fast
> > 
> > 
> > Does it run on debian proot/chroot?
> 
> No, it is fully native in termux x11
> 
> https://youtu.be/hsO-Os9jr8g

ok i couldn't get it to work ... i'll ask you in telegram ... please respond me there
